name: format check

on:
  push:
  workflow_dispatch:

jobs:
  format:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: corepack enable
      - run: node --version
      - run: yarn
      - run: yarn prettier --check '**/*.md'
